server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hero456258/microservicecloud-config.git
          username: hero456258
          password: mq316422735

